### ISSUE TITLE
Display Hidden Courses (w/Permission Handling)

### ISSUE THREAD

**Issue by zpottie** [learningworks/moodle-block_lw_courses#1]
### [Feature Request/Enhancement]

Request for an additional option to allow the display of hidden courses to users - handled with permissions if possible. This will allow a user such as a site manager, course creator, teacher, etcetera to still view hidden courses to allow easy-access to said courses. This makes managing of future/archived/shell courses easier, while still keeping it from the learner's view.

###### This may also call for the need of a filter to show only hidden courses (or show them first in the list).

**Comment by Chocolate-lightning** [comment]
I believe this functionality already exists from the course_overview block from which this block was based. Please review the current build on master and let me know.

**Comment by zpottie** [comment]
The block calls `enrol_get_my_courses()` in the [localib.php](https://github.com/learningworks/moodle-block_my_courses/blob/master/locallib.php) file to get the courses the user is enrolled. This function (in enrollib.php - Moodle's core) does a check on hidden courses and if the user is allowed to view hidden courses based on their capabilities/permissions in Moodle.

```php
    // preload contexts and check visibility
    foreach ($courses as $id=>$course) {
        context_helper::preload_from_record($course);
        if (!$course->visible) {
            if (!$context = context_course::instance($id, IGNORE_MISSING)) {
                unset($courses[$id]);
                continue;
            }
            if (!has_capability('moodle/course:viewhiddencourses', $context)) {
                unset($courses[$id]);
                continue;
            }
        }
        $courses[$id] = $course;
    }

    //wow! Is that really all? :-D

    return $courses;
```

Which means that it already addresses this issue. 🎉 

Can be closed?

**Comment by Chocolate-lightning** [comment]
During my testing I found that the block respected the roles and what they should see.
If it is a hidden course it will simply grey out. 
Closing.
