### ISSUE TITLE
Problem with this block.

### ISSUE THREAD

**Issue by ODYTRON** [learningworks/moodle-block_lw_courses#16]
after a sucessful installation of moodle-block_lw_courses, when i try to add an instance of this block from add block there is no block under the name lw_courses or my courses. 

in detail : 

Hello Mathew, Hmmm. It is impossible to get this block to work. It doesnt appear in the add block section. (only in the dashboard of the navigation block) I use adaptable as a theme i dont know if this causes the problem. Please help , your block is crucial for my platform look and feel.

**Comment by Chocolate-lightning** [comment]
Hi there,

Sorry I didn't back to you on Moodle yesterday. I was away sick. 

Do you have the latest version of the block? It installs as lw_courses but when you add a new instance in is added as my courses (lw_courses)

Kind regards,

Matt

**Comment by ODYTRON** [comment]
Actually i have the latest version, it seems that there is no problem with the installation, but there is no instance to add in the blocks section. ( the instance exists only when i click the dashboard area)
I attach a screenshot with the problem. 
![image](https://user-images.githubusercontent.com/4754095/32389200-b1ca7f6e-c0d2-11e7-9389-ba63b351048a.png)

**Comment by Chocolate-lightning** [comment]
Ah I see,

In the block_lw_courses.php you should see the applicable formats function. Currently it is set to only allow instances on the /my page. You will have to change this currently but since I have seen this query more than once I'll be changing this default to also work on the site home. 

Regards, 
Matt

**Comment by ODYTRON** [comment]
Thank you very much. Your contribution to my efforts to apply elearning staff to my lab is very important!!!!!!!

Εστάλη από τηλέφωνο Windows 10

________________________________
Από: Mathew <notifications@github.com>
Στάλθηκε: Saturday, November 4, 2017 4:10:31 AM
Προς: learningworks/moodle-block_lw_courses
Κοιν.: Odysseas Tigas; Author
Θέμα: Re: [learningworks/moodle-block_lw_courses] Problem with this block. (#16)


Ah I see,

In the block_lw_courses.php you should see the applicable formats function. Currently it is set to only allow instances on the /my page. You will have to change this currently but since I have seen this query more than once I'll be changing this default to also work on the site home.

Regards,
Matt

**Comment by Chocolate-lightning** [comment]
No worries, best of luck and enjoy the block. 

Regards,
Matt

**Comment by ODYTRON** [comment]
To recap : 
should i use  'home' instead of 'my'  in the return array ?

**Comment by Chocolate-lightning** [comment]
Hey there,

If you were wanting the block on the site home you can do the following
![screen shot 2017-11-07 at 11 16 53](https://user-images.githubusercontent.com/13307778/32467001-e22605e2-c3ad-11e7-88be-5c91cf804b15.png)

Also if you wanted the block to appear anywhere change the array to 'all' => true
