### ISSUE TITLE
Issue with Course Image

### ISSUE THREAD

**Issue by dieweswolf** [learningworks/moodle-block_lw_courses#18]
Hi there - Great block, thank you so much
However, one small issue - 
I have set an image for the course summary in the spesific course summary section - however, it is not pulling this through to the my courses block - I do not want a default image, each courses image should be different? How can I fix this
Moodle 3.4

Thanks so much
<img width="1157" alt="screen shot 2017-11-29 at 08 13 07" src="https://user-images.githubusercontent.com/5179618/33360622-2cf2ca02-d4dd-11e7-8928-dcbeffdfefa4.png">

**Comment by dieweswolf** [comment]
OOPS, Silly me. -I have been Able To Fix It - Thanks you so much, I added the image to the wrong section in the course settings. lol

**Comment by Chocolate-lightning** [comment]
Haha cheers,

As you have solved this I will close the issue. Also That is an awesome idea that I never considered.

Regards,
Matt
