### ISSUE TITLE
Progress Unavailable Text Visibility

### ISSUE THREAD

**Issue by zpottie** [learningworks/moodle-block_lw_courses#3]
Should the text that's displayed when completion tracking is not enabled (or similar text) be displayed to any type of user? Or should this information be limited to Admins, site managers, teachers, etc? Perhaps a 'restricted' version of the text can be displayed to users who have fewer permissions - E.g. "_Progress information unavailable_", "_Progress unknown_", etc.
_____
![progressunavailable](https://cloud.githubusercontent.com/assets/9076608/24434924/ddeb44ca-148e-11e7-92a6-a89001c3a164.png)

> Current error/notification message

_____

@sketchcms @Chocolate-lightning

**Comment by Chocolate-lightning** [comment]
The reason this text is rendered was for layout symmetry but since the layouts have since changed we could look at changing or removing these outputs. If you wanted to mess around I suggest branching off and doing a pull request your soloution.
