### ISSUE TITLE
Adopt the myoverview block's method to updating completion-based progress bars

### ISSUE THREAD

**Issue by rolandsherwood2** [learningworks/moodle-block_lw_courses#32]
Moodle's myoverview block displays updates a users' overall progress re. completion of activities/resources instantly. This approach would likely be preferable to most users and may reduce possible confusion resulting from the lw_courses need for the cron to run prior to updating its completion-based progress bar, as well as other issues e.g. -

https://github.com/learningworks/moodle-block_lw_courses/issues/31
https://github.com/learningworks/moodle-block_lw_courses/issues/30

**Comment by Chocolate-lightning** [comment]
Hey there,

Thanks for the suggestion! I have been sitting on these issues for a little bit but got time today to work on them. I believe this issue, #30 and #31 Have been fixed with commit: #93d2ab1

Kind regards,
Mathew
