### ISSUE TITLE
if user enrolled in remote courses, block tries to get context of remote course and fails.

### ISSUE THREAD

**Issue by danmarsden** [learningworks/moodle-block_lw_courses#35]
When the user is enrolled in a remote course block_lw_courses_get_sorted_courses adds these with a negative courseid value.

Then it tries to get the context for the course (which fails) 
https://github.com/learningworks/moodle-block_lw_courses/blob/master/renderer.php#L140

debug output.

Debug info: SELECT id,category FROM {course} WHERE id = ?
[array (
0 => -2891,
)]
Error code: invalidrecord
Stack trace:
line 1546 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
line 1522 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 6556 of /lib/accesslib.php: call to moodle_database->get_record()
line 140 of /blocks/lw_courses/renderer.php: call to context_course::instance()
line 91 of /blocks/lw_courses/block_lw_courses.php: call to block_lw_courses_renderer->lw_courses()

**Comment by Chocolate-lightning** [comment]
Hi Dan,

Thank you for raising this issue. I'll be sure to look into it. In the mean time if you have a fix please feel free to submit a pull request.
