### ISSUE TITLE
Clickable Course Block

### ISSUE THREAD

**Issue by zpottie** [learningworks/moodle-block_lw_courses#4]
I see there's some JS that makes the whole course block clickable - https://github.com/learningworks/moodle-block_my_courses/blob/master/js/custom.js#L6-L8 for commit 591e869

Perhaps styling can be added if class 'jsenabled' exists for body element to change the cursor to a 'pointer' when hovering over the courseboxes.

@sketchcms @Chocolate-lightning

**Comment by Chocolate-lightning** [comment]
@sketchcms Can you please look into this for List view please?
